### PR TITLE
Merge remote-tracking branch 'upstream/master' into linux

### PR DESCRIPTION
**Pull request by scribam**
This pull request merges the master branch from benvanik/xenia into the linux branch. Thanks to that, I was able to fix the conflict related to the .travis.yml file. AppVeyor should not throw an error anymore.

### CODE REVIEW

**Comment by scribam** [comment]
@dougvj Any chance to have it merge soon? Or should I submit directly these changes to the upstream repository?

**Comment by dougvj** [comment]
I still have some changes I would like to wrap up and push, I will try to work on that this week

**Comment by scribam** [comment]
I am looking forward to see that :slightly_smiling_face:

**Comment by scribam** [comment]
Have you had a chance to work on it? Should I close this PR and let you fix the conflict related to the .travis.yml file?

**Comment by dougvj** [comment]
Sorry, I have been swamped. I didn't even notice your message. Closing it was a good call I will fix this when I can.

**Pull request closed without merging**
